pipeline {
   agent any

   stages {

   stage('init') {
      steps {
    echo 'begin init...'

 }
}

   stage('buildModule') {
       steps {
    echo 'begin buildModule...' 
    echo '${currentBuild.previousBuild.result}'

 }


}

}
 










}

